name: Deploy to development

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches: [develop]

permissions:
    id-token: write # Required for OIDC authentication

env:
    STAGE: development
    AWS_REGION: ap-northeast-2
    AWS_ECR_REPOSITORY: app-screenshot-resizer/dev

jobs:
    CI:
        uses: ./.github/workflows/ci.yml
        secrets: inherit

    CD:
        needs: CI
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout code
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.WORKFLOW_TOKEN }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            # 2. AWS Credentials (role based)
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::499888194301:role/github_action
                  aws-region: ${{ env.AWS_REGION }}

            # 3. AWSs ECR Login
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            # 4. Build and push Docker image
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                  docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
